# -*- coding: utf-8 -*-
"""NumberGuess.cpp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IB67yUhDFMhOzwc9gX98JQ62onipNqQT
"""

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {
    int number, guess, tries = 0;

    // Initialize random number generator
    srand(time(0));
    number = rand() % 100 + 1;  // Random number between 1 and 100

    printf("Welcome to the Number Guessing Game!\n");
    printf("I'm thinking of a number between 1 and 100.\n");

    // Loop until correct guess
    do {
        printf("Enter your guess: ");
        scanf("%d", &guess);
        tries++;

        if (guess > number)
            printf("Too high! Try again.\n");
        else if (guess < number)
            printf("Too low! Try again.\n");
        else
            printf("Correct! You got it in %d tries.\n", tries);

    } while (guess != number);

    return 0;
}