# -*- coding: utf-8 -*-
"""TickTacToe.cpp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IB67yUhDFMhOzwc9gX98JQ62onipNqQT
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tic_tac_toe.cpp
# #include <iostream>
# using namespace std;
# 
# char board[3][3] = {{'1','2','3'}, {'4','5','6'}, {'7','8','9'}};
# char current_marker;
# int current_player;
# 
# bool place_marker(int slot) {
#     int row = (slot - 1) / 3;
#     int col = (slot - 1) % 3;
#     if (board[row][col] != 'X' && board[row][col] != 'O') {
#         board[row][col] = current_marker;
#         return true;
#     }
#     return false;
# }
# 
# void print_board() {
#     for (int i = 0; i < 3; i++) {
#         cout << "| ";
#         for (int j = 0; j < 3; j++) {
#             cout << board[i][j] << " | ";
#         }
#         cout << "\n";
#     }
# }
# 
# int winner() {
#     // rows and columns
#     for (int i = 0; i < 3; i++) {
#         if (board[i][0] == board[i][1] && board[i][1] == board[i][2]) return current_player;
#         if (board[0][i] == board[1][i] && board[1][i] == board[2][i]) return current_player;
#     }
#     // diagonals
#     if (board[0][0] == board[1][1] && board[1][1] == board[2][2]) return current_player;
#     if (board[0][2] == board[1][1] && board[1][1] == board[2][0]) return current_player;
#     return 0;
# }
# 
# void game() {
#     cout << "Player 1, choose your marker: ";
#     cin >> current_marker;
#     current_player = 1;
# 
#     int player_won;
# 
#     for (int i = 0; i < 9; i++) {
#         print_board();
#         int slot;
#         cout << "It's player " << current_player << "'s turn. Enter your slot: ";
#         cin >> slot;
# 
#         if (place_marker(slot) == false) {
#             cout << "Slot occupied! Try again.\n";
#             i--;
#             continue;
#         }
# 
#         player_won = winner();
#         if (player_won == 1 || player_won == 2) {
#             cout << "Player " << player_won << " wins!\n";
#             break;
#         }
# 
#         current_player = (current_player == 1) ? 2 : 1;
#         current_marker = (current_marker == 'X') ? 'O' : 'X';
#     }
# 
#     if (player_won == 0) {
#         cout << "It's a draw!\n";
#     }
# 
#     print_board();
# }
# 
# int main() {
#     game();
#     return 0;
# }
#

!g++ tic_tac_toe.cpp -o ttt

